In [106]:
import numpy as np
sudoku =[[0,6,0,7,4,9,0,0,8],
[0,0,0,0,0,0,0,0,0],
[0,8,0,0,5,0,0,0,0],
[0,0,0,0,9,0,0,0,0],
[5,0,0,1,0,0,7,0,0],
[4,0,0,0,7,0,1,3,2],
[0,0,0,8,0,2,0,0,6],
[0,0,0,0,0,0,0,0,4],
[2,0,0,4,0,0,0,0,7]]


In [107]:
def check(x,y,n):
    global sudoku
    for i in range(0,9):
        if sudoku[x][i]==n:
            return False
    for i in range(0,9):
        if sudoku[i][y]==n:
            return False
    xo=(x//3)*3
    yo=(y//3)*3
    for i in range(0,3):
        for j in range(0,3):
            if sudoku[xo+i][yo+j]==n:
                return False
    return True

In [108]:
def solve():
    global sudoku
    for x in range(9):
        for y in range(9):
            if sudoku[x][y]==0:
                for n in range(1,10):
                    if check(x,y,n):
                        sudoku[x][y]=n
                        solve()
                        sudoku[x][y]=0
                return
    print(np.matrix(sudoku))
    

In [109]:
solve()

[[3 6 1 7 4 9 2 5 8]
 [9 4 5 3 2 8 6 7 1]
 [7 8 2 6 5 1 9 4 3]
 [6 1 7 2 9 3 4 8 5]
 [5 2 3 1 8 4 7 6 9]
 [4 9 8 5 7 6 1 3 2]
 [1 7 4 8 3 2 5 9 6]
 [8 5 6 9 1 7 3 2 4]
 [2 3 9 4 6 5 8 1 7]]
